### ISSUE TITLE
How to properly intercept and reroute from middleware?

### ISSUE THREAD

**Issue by jimsimon** [vanwagonet/middle-router#93]
Example code:
```javascript
import Router from 'middle-router'

export default Router()
  .use(async ({router, path}) => {
    const loggedIn = false // TODO: Check for valid token here
    if (!loggedIn && path !== '/login') {
      return router.navigate('/login')
    }
  })
  .lazy('/login', async () => {
    return (await import(
      /* webpackChunkName: 'login' */
      './routes/login.js'
      )).default
  })
  .lazy('/', async () => {
    return (await import(
      /* webpackChunkName: 'bananas' */
      './routes/bananas.js'
      )).default
  })
```

In this example, what's the correct way to redirect the user to the "login" route?  Right now the "bananas" route is still ultimately getting rendered.  I'm essentially looking for a way to exit out of the initial page load route after issuing the navigate call.

**Comment by vanwagonet** [comment]
You can `resolve()` in that first middleware, and then the rest won't run. It's the opposite behavior you see in express, where unless you call `next` it will be done, middle-router will assume it needs to run the next one until you call `resolve`.

I might expect `resolve(router.navigate('/login'))` to work, but that probably depends on what you are expecting to do with resolved values.

**Comment by jimsimon** [comment]
Hm...that should work. I'll have to add some code in my route handler to
handle undefined resolves though.  Thanks!

**Comment by vanwagonet** [comment]
Feel free to reopen if that doesn't work for you.
